AWSTemplateFormatVersion: 2010-09-09
Description: Sample CloudFormation Template to create webserver instance.

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Description: Please select an EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro

Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: allow traffic on port 80
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: |-
          #!/bin/bash
          sudo su
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          echo "<html><body><h1>Deployed from Jenkins in DevOps Account. </h1> <br> <h4> Web server is running at: $(curl http://169.254.169.254/latest/meta-data/public-hostname)</h4></body></html>" > /var/www/html/index.html
