pipeline {
  agent {
    label 'fargate'
  }

  stages {
    stage('deploy webserver') {
      steps {
        withAWS(roleAccount:"${TEAM1_APP1_DEV_WORKLOAD_ACCOUNT}", role:"${TEAM1_APP1_DEV_WORKLOAD_JENKINS_ROLE}") {
          sh "aws cloudformation deploy --template-file file://pipeline-ec2/cfn-webserver.yaml --stack-name sample-webserver-stack"
        }
      }
    }
  }
}
