pipeline {
  agent {
    label 'fargate'
  }

  stages {
    stage('deploy webserver') {
      steps {
        withAWS(roleAccount:"${TEAM1_APP1_DEV_WORKLOAD_ACCOUNT}", role:"${TEAM1_APP1_DEV_WORKLOAD_JENKINS_ROLE}") {
          sh "jq --version"
//           script {
//             sh " 'aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query \"Vpcs[].VpcId\" --region us-east-1' > command"
//             command_var = readFile('command').trim()
//             sh "export command_var=$command_var"
//           }
          sh "aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query \"Vpcs[].VpcId\" --region us-east-1 > commandResult"
          result = readFile('commandResult').trim()
          echo "$result"
          //sh "aws cloudformation deploy --template-file sample/pipeline-ec2/cfn-webserver.yaml --stack-name sample-webserver-stack --parameter-overrides DefaultVPCId=${LookupDefaultVPCId}"
        }
      }
    }
  }
}
